INCOME_FIELDS = [
    'Total Revenue',
    'Cost Of Revenue',
    'Gross Profit',
    '',
    'Research And Development',
    'Selling General And Administration',
    'Operating Expense',
    'Operating Income',
    '',
    'Interest Expense',
    'Other Income Expense',
    'Pretax Income',
    'Tax Provision',
    'Net Income',
    '',
    'Basic EPS',
    'Diluted EPS',
    'Basic Average Shares',
    'Diluted Average Shares',
    '',
    'EBITDA',
    'Reconciled Depreciation',
]

BS_FIELDS = [
    'Cash And Cash Equivalents',
    'Other Short Term Investments',
    'Accounts Receivable',
    'Inventory',
    'Other Current Assets',
    'Current Assets',
    '',
    'Net PPE',
    'Goodwill',
    'Other Intangible Assets',
    'Long Term Equity Investment',
    'Other Non Current Assets',
    'Total Non Current Assets',
    'Total Assets',
    '',
    'Accounts Payable',
    'Current Debt',
    'Current Deferred Revenue',
    'Other Current Liabilities',
    'Current Liabilities',
    'Long Term Debt',
    'Other Non Current Liabilities',
    'Total Non Current Liabilities Net Minority Interest',
    'Total Liabilities Net Minority Interest',
    '',
    'Common Stock',
    'Additional Paid In Capital',
    'Treasury Stock',
    'Retained Earnings',
    'Stockholders Equity',
    'Total Equity Gross Minority Interest',
]

CF_FIELDS = [
    'Net Income',
    'Depreciation And Amortization',
    'Stock Based Compensation',
    'Deferred Tax',
    'Change In Receivables',
    'Change In Inventory',
    'Change In Payables And Accrued Expense',
    'Operating Cash Flow',
    '',
    'Capital Expenditure',
    'Net Business Purchase And Sale',
    'Purchase Of Investment',
    'Sale Of Investment',
    'Investing Cash Flow',
    '',
    'Issuance Of Debt',
    'Repayment Of Debt',
    'Common Stock Issuance',
    'Repurchase Of Capital Stock',
    'Common Stock Dividend Paid',
    'Financing Cash Flow',
    '',
    'Changes In Cash',
    'Free Cash Flow',
]
