INCOME_FIELDS = [
    '  Total Revenue',
    '  Cost Of Revenue',
    'Gross Profit',
    '',
    '  Research And Development',
    '  Selling General And Administration',
    '    Selling And Marketing Expense',
    '    General And Administrative Expense',
    '  Restructuring And Mergern Acquisition',
    '  Operating Expense',
    'Operating Income',
    '',
    '  Interest Expense',
    '  Other Income Expense',
    '    Gain On Sale Of Security',
    'Pretax Income',
    '  Tax Provision',
    'Net Income',
    '',
    '  Total Unusual Items',
    'Normalized Income',
    '',
    '  Basic EPS',
    '  Diluted EPS',
    '  Basic Average Shares',
    '  Diluted Average Shares',
    '',
    'EBITDA',
    '  Reconciled Depreciation',
]

BS_FIELDS = [
    '  Cash And Cash Equivalents',
    '  Other Short Term Investments',
    'Cash Cash Equivalents And Short Term Investments',
    '  Restricted Cash',
    '  Accounts Receivable',
    '  Inventory',
    '  Other Current Assets',
    'Current Assets',
    '',
    '  Net PPE',
    '  Goodwill',
    '  Other Intangible Assets',
    'Goodwill And Other Intangible Assets',
    '  Long Term Equity Investment',
    '  Other Non Current Assets',
    'Total Non Current Assets',
    '',
    'Total Assets',
    '',
    '  Accounts Payable',
    '  Current Debt',
    '  Current Deferred Revenue',
    '  Other Current Liabilities',
    'Current Liabilities',
    '',
    '  Long Term Debt',
    '  Capital Lease Obligations',
    '  Other Non Current Liabilities',
    'Total Non Current Liabilities Net Minority Interest',
    '',
    'Total Liabilities Net Minority Interest',
    '  Total Debt',
    '',
    '  Common Stock',
    '  Additional Paid In Capital',
    '  Treasury Stock',
    '  Retained Earnings',
    '  Gains Losses Not Affecting Retained Earnings',
    '  Ordinary Shares Number',
    'Stockholders Equity',
    '',
    'Total Equity Gross Minority Interest',
    '',
    'Working Capital',
]

CF_FIELDS = [
    '  Net Income From Continuing Operations',
    '  Depreciation And Amortization',
    '  Stock Based Compensation',
    '  Deferred Tax',
    '  Change In Receivables',
    '  Change In Inventory',
    '  Change In Payables And Accrued Expense',
    'Operating Cash Flow',
    '',
    '  Capital Expenditure',
    '  Net Business Purchase And Sale',
    '  Purchase Of Investment',
    '  Sale Of Investment',
    'Investing Cash Flow',
    '',
    '  Issuance Of Debt',
    '  Repayment Of Debt',
    '  Common Stock Issuance',
    '  Repurchase Of Capital Stock',
    '  Common Stock Dividend Paid',
    'Financing Cash Flow',
    '',
    'Changes In Cash',
    'Free Cash Flow',
    '',
    '  Interest Paid Supplemental Data',
    '  Income Tax Paid Supplemental Data',
]
